provider:
    credentials: xxxx
    region: us-east-1
    vendor: aws
    cluster: xxxx
train:
    actions:
      on_build_start: 
        - echo "did this work?"
        -  apt-get install ffmpeg libsm6 libxext6  -y
